version: '2.1'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - postgres:/var/lib/postgresql/data

    webserver:
        image: bd/airflow
        restart: always
        depends_on:
            - postgres
        environment:
            - EXECUTOR=Local
            - AIRFLOW__CORE__LOGGING_LEVEL=WARN
        volumes:
            - ./dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    local-scheduler:
        image: bd/airflow
        restart: always
        depends_on:
            - postgres
        environment:
            - EXECUTOR=Local
            - AIRFLOW__CORE__LOGGING_LEVEL=INFO
        volumes:
            - ./dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        command: local-scheduler
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-schedulerr.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

volumes:
    # this creates a volume mapped to a host directory which is 
    # God knows where, entireley managed by Docker (itself running as root).
    # Postgres runs as root too, so yea, it has the correct owner.
    postgres: {}
